### ISSUE TITLE
We hope there is a new feature that gives priority to the first result.

### ISSUE THREAD

**Issue by zzhuang94** [networkservicemesh/fanout#47]
We have this scenario:
1. Multiple upstream servers are configured
2. One of them is down
3. Query a non-existent domain and expect `NXDOMAIN` result
4. But in fact, we get `"connection timed out"` result

**If we use the `timeout` to set the request timeout, it may affect the result of normal domains.**

**Therefore, we hope there is a new feature that gives priority to the first result, whether it is negative or not, as long as it is a standard DNS result (except for timeout).**

**Comment by denis-tingaikin** [comment]
Hmm... It seems to me that the root cause is that one of the upstream servers is long looking for the entry (that it actually doesn't know) finally it makes timeout error.


Is that server under your control?

**Comment by edwarnicke** [comment]
@zzhuang94 Its seems that you have the opposite problem to the one initially anticipated for fanout.  fanout had been thinking in terms of multiple not-necessarily equivalent DNS servers.  In such an environment, accepting a negative result simply because its first may result in missing a positive result that simply comes in later.  So the default rule was "first non-negative result is returned"

In your environment, your DNS servers are equivalent.  In such a situation I can see why you want the "first response, whether positive or negative" as the outcome.  It was not a use case anticipated originally, but I can see why you have it and why you desire this behavior as an option.

**Comment by zzhuang94** [comment]
thanks for mergering！

**Comment by zzhuang94** [comment]
thanks for merging !
